# config.yaml

zarr_base_dir: "/project/cil/home_dirs/scadavidsanchez/flexible-damage-funcs/dataset/mortality/damages"
output_dir: "./results_mortality_fe"
input_dir: "./results_mortality_fe"

# Processing resources
n_workers: 20
memory_limit_gb: 180

# Scope
ssps: ["SSP3"] # will look for mortality_SSP3.zarr, etc.
rcps: ["rcp45", "rcp85"]

test_mode: false
test_batch: "batch0"
test_gcm_count: 2
generate_plots: true

# =================================================================================
# REGIONAL ESTIMATION CONFIG
# =================================================================================

output_dir: "./results_mortality_fe"
regions_per_job: 50      
n_jobs_per_task: 8        
n_parallel_jobs: 8 

gamma_statistics_csv: "./results_mortality_fe/gamma_statistics.csv"