# config.yaml

zarr_base_dir: "/project/cil/home_dirs/scadavidsanchez/projects/flex-damage-functions-ir/dataset/mortality/damages"
output_dir: "/project/cil/home_dirs/scadavidsanchez/projects/flex-damage-functions-ir/results/mortality"
input_dir: "/project/cil/home_dirs/scadavidsanchez/projects/flex-damage-functions-ir/results/mortality"

# Processing resources
n_workers: 25
memory_limit_gb: 200

# Scope
ssps: ["SSP2", "SSP3", "SSP4", "SSP5"] # will look for mortality_SSP*.zarr, etc.
# "SSP1" does not have all rcp values
rcps: ["rcp45", "rcp85"]

test_mode: false
test_batch: "batch0"
test_gcm_count: 2
generate_plots: true

# =================================================================================
# REGIONAL ESTIMATION CONFIG
# =================================================================================

output_dir: "./results/mortality"
regions_per_job: 50      
n_jobs_per_task: 8        
n_parallel_jobs: 8 

gamma_statistics_csv: "/project/cil/home_dirs/scadavidsanchez/projects/flex-damage-functions-ir/results/mortality/gamma_statistics.csv"